configured_endpoints: 22
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/weio-ltd/vat-sense-d0dc12ecd758a0fe9bb17a6bd5adabadcc715ae86771feec4faced45bd60f451.yml
openapi_spec_hash: dc99fb074e506e0fca495dcbcd8511ab
config_hash: 9bf5dcba4e8af734204feccadf9193d2
